spring.application.name=mall-member
server.port=10014
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true

spring.session.store-type=redis

spring.data.redis.host=${SERVER_IP:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:123456}

spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${SERVER_IP:localhost}:3306/mall_ums
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:admin123}
