spring.application.name=mall-member
server.port=10014
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true
spring.profiles.active=prod