spring.application.name=mall-gateway
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
server.port=88

spring.cloud.gateway.httpclient.pool.max-idle-time=2000ms
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true