#!/usr/bin/env bash
# ============================================================================
# install-infra-basic.sh —— 单独安装 Redis / MinIO / Nginx
#
# 用途：这三者通常已在宿主或单独一组，独立成脚本，只装它们。
#  （主脚本 install-infra.sh 不包含这三者，两者搭配使用。）
#
# 说明：
#  - Redis 密码需与业务服务配置一致（spring.data.redis.password）
#  - MinIO 密钥需与配置一致（minio.accessKey / minio.secretKey）
#  - Nginx 生成反代配置并暴露 80（若宿主已装 nginx，改用其自身 reload，勿重复占 80）
# ============================================================================

set -e

# ---------------- 可配置项 ----------------
# 自动探测本服务器地址（取不到才用 localhost）
detect_ip() {
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip=$(ip route get 1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
  fi
  if [ -z "$ip" ] && command -v hostname >/dev/null 2>&1; then
    ip=$(hostname -I 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i!="127.0.0.1"){print $i; break}}')
  fi
  [ -z "$ip" ] && ip="127.0.0.1"
  echo "$ip"
}
SERVER_IP="${SERVER_IP:-$(detect_ip)}"
# 数据目录根（默认 /data/mall；也可 DATA_ROOT=xxx bash install-infra-basic.sh）
DATA_ROOT="${DATA_ROOT:-/data/mall}"

REDIS_IMAGE="${REDIS_IMAGE:-redis:7-alpine}"
REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_PASSWORD="${REDIS_PASSWORD:-admin123}"            # 与 spring.data.redis.password 一致
REDIS_DATA_DIR="${REDIS_DATA_DIR:-$DATA_ROOT/redis}"

MINIO_IMAGE="${MINIO_IMAGE:-minio/minio:latest}"
MINIO_PORT="${MINIO_PORT:-9000}"                     # S3 API
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9001}"     # 控制台
MINIO_USER="${MINIO_USER:-minioadmin}"               # 与 minio.accessKey 一致
MINIO_PASS="${MINIO_PASS:-minioadmin}"               # 与 minio.secretKey 一致
MINIO_DATA_DIR="${MINIO_DATA_DIR:-$DATA_ROOT/minio}"

NGINX_IMAGE="${NGINX_IMAGE:-nginx:alpine}"
NGINX_HTTP_PORT="${NGINX_HTTP_PORT:-8088}"         # nginx 宿主机监听端口（避开已被占用的 80；映射到容器 80）
NGINX_FRONTEND_ROOT="${NGINX_FRONTEND_ROOT:-$DATA_ROOT/web}"   # 前端静态文件目录（后续部署 vite 产物）
NGINX_HTML_CONTAINER="${NGINX_HTML_CONTAINER:-/usr/share/nginx/html}"   # 容器内 nginx 根（挂载点）
NGINX_ADMIN_ROOT="${NGINX_ADMIN_ROOT:-$DATA_ROOT/web-admin}"   # 管理后台静态目录（宿主）→ /admin/
NGINX_ADMIN_HTML_CONTAINER="${NGINX_ADMIN_HTML_CONTAINER:-/usr/share/nginx/html-admin}"   # 容器内后台挂载点
GATEWAY_HOST="${GATEWAY_HOST:-$SERVER_IP}"           # 网关所在服务器地址（nginx 反代目标）
GATEWAY_PORT="${GATEWAY_PORT:-88}"                   # 网关对外端口（nginx 反代目标）
NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-mall.example.com}"

wait_for() {
  local port="$1" name="$2" i=0
  echo "==> 等待 $name 就绪( $port )..."
  until (echo > /dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1; do
    i=$((i+1)); [ "$i" -gt 60 ] && { echo "  等待超时：$name"; return 1; }
    sleep 2
  done
  echo "  $name 就绪。"
}

echo "============================================================"
echo " 安装基础组件 (Redis / MinIO / Nginx)"
echo "============================================================"

# ---------------------------------------------------------------------
# 1. Redis
# ---------------------------------------------------------------------
echo "-------- [1/3] Redis --------"
mkdir -p "$REDIS_DATA_DIR"
docker rm -f redis >/dev/null 2>&1 || true
docker run -d --name redis \
  -p "${REDIS_PORT}:6379" \
  -v "$REDIS_DATA_DIR":/data \
  -e "REDIS_PASSWORD=${REDIS_PASSWORD}" \
  --restart unless-stopped \
  "$REDIS_IMAGE" \
  redis-server --requirepass "$REDIS_PASSWORD" --appendonly yes
wait_for "$REDIS_PORT" "Redis"

# ---------------------------------------------------------------------
# 2. MinIO
# ---------------------------------------------------------------------
echo "-------- [2/3] MinIO --------"
mkdir -p "$MINIO_DATA_DIR"
docker rm -f minio >/dev/null 2>&1 || true
docker run -d --name minio \
  -p "${MINIO_PORT}:9000" -p "${MINIO_CONSOLE_PORT}:9001" \
  -e "MINIO_ROOT_USER=${MINIO_USER}" \
  -e "MINIO_ROOT_PASSWORD=${MINIO_PASS}" \
  -v "$MINIO_DATA_DIR":/data \
  --restart unless-stopped \
  "$MINIO_IMAGE" server /data --console-address ":9001"
wait_for "$MINIO_PORT" "MinIO"

# ---------------------------------------------------------------------
# 3. Nginx（反向代理到网关；若宿主已装 nginx，请用它的配置而非容器）
# ---------------------------------------------------------------------
echo "-------- [3/3] Nginx --------"
mkdir -p "$DATA_ROOT/nginx/conf.d"
mkdir -p "$NGINX_FRONTEND_ROOT"
mkdir -p "$NGINX_ADMIN_ROOT"
cat > "$DATA_ROOT/nginx/conf.d/mall.conf" <<EOF
# auto-generated by install-infra-basic.sh
server {
    # 容器内 nginx 监听 80；宿主机 ${NGINX_HTTP_PORT} 由 `-p ${NGINX_HTTP_PORT}:80` 映射
    listen       80;
    server_name  ${NGINX_SERVER_NAME};

    # 前端静态（Vue SPA），把构建产物(如 vite/dist)放到 ${NGINX_FRONTEND_ROOT}（挂到容器的 ${NGINX_HTML_CONTAINER}）
    root   ${NGINX_HTML_CONTAINER};
    index  index.html;
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # 管理后台（mall-admin）→ /admin/；构建时前端 base 需设为 /admin/
    location /admin/ {
        alias ${NGINX_ADMIN_HTML_CONTAINER}/;
        try_files \$uri \$uri/ /admin/index.html;
    }

    # API / 网关，转发到网关（网关再经 Nacos 路由到各服务）
    location /api/ {
        proxy_pass http://${GATEWAY_HOST}:${GATEWAY_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
docker rm -f nginx >/dev/null 2>&1 || true
docker run -d --name nginx \
  -p "${NGINX_HTTP_PORT}:80" \
  -v "$DATA_ROOT/nginx/conf.d:/etc/nginx/conf.d" \
  -v "$NGINX_FRONTEND_ROOT:$NGINX_HTML_CONTAINER:ro" \
  -v "$NGINX_ADMIN_ROOT:$NGINX_ADMIN_HTML_CONTAINER:ro" \
  --restart unless-stopped \
  "$NGINX_IMAGE"
wait_for "$NGINX_HTTP_PORT" "Nginx"

echo
echo "============================================================"
echo " 基础组件安装完成 ✔    本机服务地址: ${SERVER_IP}"
echo " 提示：确保业务配置里的 Redis 密码 / MinIO 密钥与本脚本一致；"
echo "       服务间访问请用 ${SERVER_IP}（容器内 localhost 指容器自身）。"
echo "============================================================"
