#!/usr/bin/env bash
# ============================================================================
# install-nginx.sh —— 只安装 mall 的 nginx 容器（独立于 Redis/MinIO）
#
# 用于：宿主机已有其它 nginx/容器占用 80（如 llmops-nginx），mall 用 8088 入口。
# 作用：
#   - 起一个 mall 专用 nginx 容器（--name nginx，监听 8088）
#   - 前端静态：挂载 /data/mall/web（部署 vite/dist 产物）
#   - 反代 /api -> 网关（默认 本机IP:88，自动探测；可用 GATEWAY_HOST/GATEWAY_PORT 覆盖）
#
# 用法：
#   bash install-nginx.sh                         # 自动探测本机 IP 作网关地址
#   GATEWAY_HOST=<服务器IP> bash install-nginx.sh   # 显式指定网关主机
# ============================================================================
set -e

# ---------------- 探测本机 IP（取不到才用 localhost） ----------------
detect_ip() {
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip=$(ip route get 1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
  fi
  if [ -z "$ip" ] && command -v hostname >/dev/null 2>&1; then
    ip=$(hostname -I 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i!="127.0.0.1"){print $i; break}}')
  fi
  [ -z "$ip" ] && ip="127.0.0.1"
  echo "$ip"
}
SERVER_IP="${SERVER_IP:-$(detect_ip)}"
DATA_ROOT="${DATA_ROOT:-/data/mall}"

# ---------------- 可配置项 ----------------
NGINX_IMAGE="${NGINX_IMAGE:-nginx:alpine}"
NGINX_CONTAINER="${NGINX_CONTAINER:-nginx}"           # mall 的 nginx 容器名
NGINX_HTTP_PORT="${NGINX_HTTP_PORT:-8088}"            # 宿主机对外监听端口（由 -p 映射到容器 80）
NGINX_FRONTEND_ROOT="${NGINX_FRONTEND_ROOT:-$DATA_ROOT/web-ui}"   # 前端静态目录（宿主）
NGINX_HTML_CONTAINER="${NGINX_HTML_CONTAINER:-/usr/share/nginx/html}"   # 容器内 nginx 根目录（挂载点）
NGINX_ADMIN_ROOT="${NGINX_ADMIN_ROOT:-$DATA_ROOT/mall-admin}"   # 管理后台静态目录（宿主）→ /admin/
NGINX_ADMIN_HTML_CONTAINER="${NGINX_ADMIN_HTML_CONTAINER:-/usr/share/nginx/html-admin}"   # 容器内后台挂载点
NGINX_CONF_DIR="${NGINX_CONF_DIR:-$DATA_ROOT/nginx/conf.d}"
GATEWAY_HOST="${GATEWAY_HOST:-$SERVER_IP}"            # 网关所在主机（nginx /api 反代目标）
GATEWAY_PORT="${GATEWAY_PORT:-88}"                    # 网关端口
NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-mall.example.com}"

wait_for() {
  local port="$1" name="$2" i=0
  echo "==> 等待 $name 就绪( $port )..."
  until (echo > /dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1; do
    i=$((i+1)); [ "$i" -gt 60 ] && { echo "  等待超时：$name"; return 1; }
    sleep 2
  done
  echo "  $name 就绪。"
}

echo "============================================================"
echo " 安装 mall 的 nginx 容器  监听=${NGINX_HTTP_PORT}  反代网关=${GATEWAY_HOST}:${GATEWAY_PORT}"
echo "============================================================"
mkdir -p "$NGINX_CONF_DIR"
mkdir -p "$NGINX_FRONTEND_ROOT"
mkdir -p "$NGINX_ADMIN_ROOT"
cat > "$NGINX_CONF_DIR/mall.conf" <<EOF
# auto-generated by install-nginx.sh
server {
    # 容器内 nginx 监听 80；宿主机 ${NGINX_HTTP_PORT} 由 \`-p ${NGINX_HTTP_PORT}:80\` 映射
    listen       80;
    server_name  ${NGINX_SERVER_NAME};

    # 前端静态（Vue SPA），把构建产物(如 vite/dist)放到 ${NGINX_FRONTEND_ROOT}（挂到容器的 ${NGINX_HTML_CONTAINER}）
    root   ${NGINX_HTML_CONTAINER};
    index  index.html;
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # 管理后台（mall-admin）→ /admin/；构建时前端 base 需设为 /admin/
    location /admin/ {
        alias ${NGINX_ADMIN_HTML_CONTAINER}/;
        try_files \$uri \$uri/ /admin/index.html;
    }

    # API / 网关，转发到网关（网关再经 Nacos 路由到各服务）
    location /api/ {
        proxy_pass http://${GATEWAY_HOST}:${GATEWAY_PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

docker rm -f "$NGINX_CONTAINER" >/dev/null 2>&1 || true
docker run -d --name "$NGINX_CONTAINER" \
  -p "${NGINX_HTTP_PORT}:80" \
  -v "$NGINX_CONF_DIR:/etc/nginx/conf.d" \
  -v "$NGINX_FRONTEND_ROOT:$NGINX_HTML_CONTAINER:ro" \
  -v "$NGINX_ADMIN_ROOT:$NGINX_ADMIN_HTML_CONTAINER:ro" \
  --restart unless-stopped \
  "$NGINX_IMAGE"
wait_for "$NGINX_HTTP_PORT" "Nginx"

echo
echo "============================================================"
echo " mall nginx 容器已启动（${NGINX_CONTAINER}）"
echo " 前端: http://${SERVER_IP}:${NGINX_HTTP_PORT}/"
echo " API : http://${SERVER_IP}:${NGINX_HTTP_PORT}/api/**  -> 网关 ${GATEWAY_HOST}:${GATEWAY_PORT}"
echo " 前端产物放到: ${NGINX_FRONTEND_ROOT}"
echo "============================================================"
