spring:
  config:
    import: "nacos:mall-weapp.yaml"
  cloud:
    nacos:
      server-addr: ${SERVER_IP:localhost}:8848
      discovery:
        server-addr: ${SERVER_IP:localhost}:8848
  application:
    name: mall-weapp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      host: ${SERVER_IP:localhost}
      port: 6379
      password: CHANGE_ME
server:
  port: 10021
logging:
  level:
    com.mall.weapp: debug
