spring.application.name=mall-ware
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
# RabbitMQ??
spring.rabbitmq.host=${SERVER_IP:localhost}
spring.rabbitmq.port=5672
# ??????
spring.rabbitmq.virtual-host=/
# ??ack??????????????
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true
server.port=10017