server.port=10016
spring.profiles.active=prod
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
spring.application.name=mall-cart
spring.data.redis.host=${SERVER_IP:localhost}
spring.data.redis.port=6379
spring.data.redis.password=CHANGE_ME
spring.session.store-type=redis
#配置线程池
mall.thread.coreSize=20
mall.thread.maxSize=200
mall.thread.keepAliveTime=10

spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*