# 应用服务 WEB 访问端口
server.port=10020
spring.application.name=mall-seckill
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
# RabbitMQ??
spring.rabbitmq.host=${SERVER_IP:localhost}
spring.rabbitmq.port=5672
# ??????
spring.rabbitmq.virtual-host=/
# sentinel
spring.cloud.sentinel.transport.port=8719
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true
logging.level.org.springframework.cloud.openfeign=debug
# ????
management.zipkin.tracing.endpoint=http://${SERVER_IP:localhost}:9411/
# ??????
# ?????
management.tracing.sampling.probability=1.0

spring.data.redis.host=${SERVER_IP:localhost}
spring.data.redis.port=6379
spring.data.redis.password=CHANGE_ME

spring.session.store-type=redis

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss