spring.application.name=mall-third-party
server.port=10022
spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true