apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-pvc
  namespace: kubesphere-devops-worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: tekton-git-pvc
#  # namespace: kubesphere-devops-worker
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi