spring.application.name=mall-order
server.port=10015
spring.cloud.nacos.discovery.server-addr=${SERVER_IP:localhost}:8848
spring.rabbitmq.host=${SERVER_IP:localhost}
spring.rabbitmq.port=5672
#spring.rabbitmq.username=root
#spring.rabbitmq.password=CHANGE_ME
spring.rabbitmq.virtual-host=/
# 开启发送端确认
spring.rabbitmq.publisher-confirm-type=correlated
# 开启发送端消息抵达对列的确认
spring.rabbitmq.publisher-returns=true
# 只要消息抵达Queue，就会异步发送优先回调returnfirm
spring.rabbitmq.template.mandatory=true
#手动ack消息
spring.rabbitmq.listener.simple.acknowledge-mode=manual
#session存入redis
spring.session.store-type=redis
#配置线程池
mall.thread.coreSize=20
mall.thread.maxSize=200
mall.thread.keepAliveTime=10

spring.mvc.format.date=yyyy-MM-dd HH:mm:ss


spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${SERVER_IP:localhost}:3306/mall_oms
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:admin123}

spring.data.redis.host=${SERVER_IP:localhost}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:123456}

#????????
alipay.app_id=9021000133698831
alipay.merchant_private_key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCCagRtHcLuKwNddYmA7B2WYqxlCBUThL2FXVRXRLBAovf096GBotEhFfLcZhNokpAQFWwD7zXMzvGWuVnmiamjSYBIiZJqitiMKcb1NVOUs1uE+8F4WWn/lH8Rxha+mAVzgf4t2L1tS1G/B/cbmbdEDfzpI5KEHFwkMxeYhkv3rZ3BiRAF59LC6pN3QMjajAAIZS3UFUUh13rvhe7Bbo/Q4vBobkBfRwSFtt9/kiEClO5EvFRZzjUv2n2SlOrfBjYWxUB/ehQLQMtzyoYJmKZ/U9rDm2/TMPng0w+ZI7OLVZVwEgUUPbztYBP11tS3BLevZpwsow3hZHS25qs12cHlAgMBAAECggEAGy84PvqOMJE8wVWH1Rziyf9FikXWBtyLmOosc4h46PBPmXuo6dnjl+74UeLhNtIeP4wHmQZbA5c7mryGNd0KRGRE3ln28EiC/SyUMXbtNjjw4daMrKaOxtzQZAcTpKURtdMqBaqBSfACWTyy0MkI/6Gez4Y/u1QiDNWtnHiaC0WT8v5g9uTQYYgCD+Qu7uXB3w2fNuM9Ghi7ATEgHHCdBzDo/ufURJ7amK1WEj0sWZGRgKIC76i5c2vrWpBIg3DT06pFcUp985IsEQNYxHzqQ9YaD5PflWaBvcC1J55vmjzWwG409H/txp3uFAyoQSIk6BjF3Z0r34GyrwXwRsM9QQKBgQDIsSpPZqq67piSnkAI0T67kzh9T1buoJOJCw2s/O23LvXxXqYcbfa6iy5Dd5Cr+xlSRifxsH6l4MG1OzdDnee/P09rhr5JmzPRXQaT2e/+vdufgqn3tZw/Yxt6f85IiHCKr7fO57nywwgOBNEjHRNbiPhvU+ARF35w+JulMJ5eVQKBgQCmWr2v+exSHxVjg0192NQe+3id618CqIJO13sZgS1yX/bGVgRsCzDIqpLTxTt7djJ8kIgjSmbVCSxB0fwrTEM533XPqGYNmUtBRtfZ+lULXFg1Jo8teJjPn9VS3hZMnzrZqupKz8GuWIX/Mhc1n/guLXt/6V05FGCRNn7B8g1FUQKBgQCY3lpcINfri9Kr297q2HfwaTOeP9D381huCv1fx0lLP3oXYQEmppxJe7rBqVGJrrqa8NV8Q/Q0Zf8nDPQLjTv5cUANp5VKe+38i992v4sPf47K8byF8tAReGx14uQ+W69d9HsOH3SEdgqsov6qwHr+Plb+deU3H64wXy4vpdj8AQKBgBWi/8D/tKkJufJzhYS0ywIsmwePMZBa8nfmtvAeSRbzPFmXnoOfAP1YkjhREud//BkPg2Vzq+RRiRwWf8Hx7Vx9oAkeUge6xHr9B94mHSGZJS/kkALOCLIYi9p3YFce7ryY6lhIpVxTzznd/f7Pi6wV5lZAuAtQhy7b86iuHuPBAoGAcMk5WX6enp4TbQsz+DUfRZO4QNL7q8BfFnt5ClOsj/cTti3ZRQE0S1lEXlhqiCtpptTJDoRcyJs3PWEB96QPsLuJ74x30CyxNhXqc/nhJCPxOQrMTUMNQfY2wSRKU3YufB0K/u20XoXqQzVCoGPhsc8F6DY3OocTo4fpKZ/Y9SI=
alipay.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyjqEGLOWBki5OETfF4AoI9EwPlT74blMThArTwpBeyzVrsC5kj5rcEUAXWNUrvo0bQXB2PWQCGfSE68wnOr5euKF/eRDS5eif94q4MMLFEsD9Skm/INKAGvvpTejDWsqqH+L7G61akuwNzt5QY4Q00Fj3CTM2UyPMDAIytjVUjVsAK4vX1WmqxZ6U5tbAbEn9jgsE+yUmS996WNjoh7M6e9GtaJ8+zw4ZDA3muDu06lazK30zgHCCIXLaBLqyVTbxPkGwaOeDkTEKE6v3jKIhqOqd2bIufpxLd9bF83E17S+qceKxc7oIRsTbOaSrVdT+1UZD2RLDuBFGYWjzOiLSwIDAQAB
alipay.notify_url=http://CHANGE_ME_PUBLIC_IP/payed/notify
alipay.return_url=http://${SERVER_IP:localhost}/memberOrder.html
alipay.sign_type=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do

spring.cloud.sentinel.transport.dashboard=${SERVER_IP:localhost}:8333
management.endpoints.web.exposure.include=*
feign.sentinel.enabled=true
